server:
  port: 8888

spring:
  application:
    name: gateway-application

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: yudaoyuanma # 路由的编号
          uri: http://www.iocoder.cn # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/blog
          filters:
            - StripPrefix=1
        - id: oschina # 路由的编号
          uri: https://www.oschina.net # 路由的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/oschina
          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
            - StripPrefix=1

      # Reactor Netty 相关配置Reactor Netty 提供 Wiretap（窃听）功能，让 Reactor Netty 打印包含请求和响应信息的日志，例如说请求和响应的 Header、Body 等等。
      #
      #开启 Reactor Netty 的 Wiretap 功能一共有三个配置项：
      #
      #设置 reactor.netty 配置项为 DEBUG 或 TRACE。
      #设置 spring.cloud.gateway.httpserver.wiretap 配置项为 true，开启 HttpServer Wiretap 功能。
      #设置 spring.cloud.gateway.httpclient.wiretap 配置项为 true，开启 HttpClient Wiretap 功能。
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

logging:
  level:
    reactor.netty: DEBUG
    org.springframework.cloud.gateway: TRACE
